# CI Guardrails:
# - Resolve API base once; never curl a blank URL (API_BASE_STAGING -> STAGING_BASE).
# - Skip posting to Notion/GitHub when secrets/vars are missing.
# - Normalize: ROADMAP_DATABASE_ID = ROADMAP_DATABASE_ID || NOTION_DATABASE_ID.
# - Route contract: /health = .ok only; /projections = trust headers + schema.
# - Use scripts + jq; avoid inline JSON in YAML.

name: Frontend CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}-${{ github.run_attempt }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Boot
        run: echo "runner up:$GITHUB_RUN_ID/$GITHUB_RUN_ATTEMPT on $GITHUB_REF"

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Boot
        run: echo "e2e runner up:$GITHUB_RUN_ID/$GITHUB_RUN_ATTEMPT on $GITHUB_REF"

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx playwright install
      - name: Run E2E Tests
        run: |
          export NEXT_PUBLIC_API_BASE="https://customvenom-workers-api-staging.jdewett81.workers.dev"
          npx playwright test --reporter=line

  guardrails:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Boot
        run: echo "guardrails runner up:$GITHUB_RUN_ID/$GITHUB_RUN_ATTEMPT on $GITHUB_REF"

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Check for NextAuth Yahoo references
        run: |
          if grep -r "/api/auth/signin/yahoo" src/; then
            echo "❌ Found NextAuth Yahoo references in src/ - these should be removed"
            exit 1
          fi
          echo "✅ No NextAuth Yahoo references found in src/"

      - name: Check for missing credentials in API calls
        run: |
          # Check for fetch calls to api.customvenom.com without credentials: 'include'
          if grep -r "fetch.*api\.customvenom\.com" src/ | grep -v "credentials.*include"; then
            echo "❌ Found fetch calls to api.customvenom.com without credentials: 'include'"
            echo "All API calls must include credentials: 'include' for cookie-based auth"
            exit 1
          fi
          echo "✅ All API calls include credentials: 'include'"
