# CI Guardrails:
# - Resolve API base once; never curl a blank URL (API_BASE_STAGING -> STAGING_BASE).
# - Skip posting to Notion/GitHub when secrets/vars are missing.
# - Normalize: ROADMAP_DATABASE_ID = ROADMAP_DATABASE_ID || NOTION_DATABASE_ID.
# - Route contract: /health = .ok only; /projections = trust headers + schema.
# - Use scripts + jq; avoid inline JSON in YAML.

name: Frontend CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}-${{ github.run_attempt }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Boot
        run: echo "runner up:$GITHUB_RUN_ID/$GITHUB_RUN_ATTEMPT on $GITHUB_REF"

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
