name: docs-lint

on:
  pull_request:
    paths:
      - 'README.md'
      - 'docs/**/*.md'
      - '.github/**/*.md'
  push:
    branches: [main]
    paths:
      - 'README.md'
      - 'docs/**/*.md'
      - '.github/**/*.md'
  workflow_dispatch:

jobs:
  markdown:
    name: Markdownlint (informational)
    runs-on: ubuntu-latest
    # Non-blocking: reports status but won't fail the check
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install deps
        run: npm ci

      - name: Lint key docs
        run: npm run lint:md:key
