name: e2e
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: e2e-${{ github.ref }}-${{ github.run_attempt }}
  cancel-in-progress: true

jobs:
  playwright:
    runs-on: ubuntu-22.04
    timeout-minutes: 25
    steps:
      - name: Boot
        run: |
          echo "runner up: $GITHUB_RUN_ID @ $GITHUB_RUN_ATTEMPT on $GITHUB_REF"

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.11.1'
          cache: 'npm'

      - name: Install deps (non-strict)
        run: npm install --no-audit --no-fund

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE_STAGING }}
        run: |
          set -euo pipefail
          if [ -z "${NEXT_PUBLIC_API_BASE:-}" ]; then
            echo "::error ::Missing NEXT_PUBLIC_API_BASE_STAGING secret"; exit 1
          fi
          echo "API: $NEXT_PUBLIC_API_BASE"
          npx playwright test --reporter=line

      # Only on failure: upload artifacts for instant diagnosis
      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: playwright-report
          path: playwright-report
      - name: Upload Playwright traces
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: playwright-traces
          path: test-results
