name: e2e
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: e2e-${{ github.ref }}-${{ github.run_attempt }}
  cancel-in-progress: true

jobs:
  playwright:
    runs-on: ubuntu-22.04
    timeout-minutes: 25
    steps:
      - name: Boot
        run: |
          echo "runner up: $GITHUB_RUN_ID @ $GITHUB_RUN_ATTEMPT on $GITHUB_REF"

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'npm'

      - name: Install deps (strict, after lock sync)
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE_STAGING }}
        run: |
          set -euo pipefail
          if [ -z "${NEXT_PUBLIC_API_BASE:-}" ]; then
            echo "::error ::Missing NEXT_PUBLIC_API_BASE_STAGING secret"; exit 1
          fi
          echo "API: $NEXT_PUBLIC_API_BASE"
          npx playwright test --reporter=line

      # Only on failure: upload artifacts for instant diagnosis
      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
      - name: Upload Playwright traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results
