name: Guardrails

on: [push, pull_request]

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Guardrails check
        run: bash scripts/guardrails-check.sh