name: QA Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  qa:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci || npm i --no-audit --no-fund
      
      - name: Run build
        run: npm run build || true
      
      - name: Run typecheck
        run: npm run typecheck
      
      - name: Run lint
        run: npm run lint

