name: Trust Gate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trust-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Trust Gate Tests
        run: npx playwright test tests/trust-snapshot.spec.ts tests/health.spec.ts tests/prod-smoke.spec.ts
        env:
          NEXT_PUBLIC_API_BASE: https://customvenom-workers-api-staging.jdewett81.workers.dev
