name: Weekly Smoke Test
on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  weekly-smoke:
    runs-on: ubuntu-latest
    env:
      BASE: https://customvenom.com
    steps:
      - name: Run weekly smoke test
        run: |
          echo "== Weekly Smoke Test =="
          echo "Testing: $BASE"

          echo "`n== /api/health headers =="
          curl -sSD - "$BASE/api/health" -o /dev/null | grep -Ei '^(HTTP/|cache-control|x-request-id|access-control-allow-origin)' || true

          echo "`n== /api/projections?week=2025-06 headers =="
          curl -sSD - "$BASE/api/projections?week=2025-06" -o /dev/null | grep -Ei '^(HTTP/|cache-control|x-request-id|access-control-allow-origin)' || true

          echo "`n== /api/projections body fields =="
          curl -sS "$BASE/api/projections?week=2025-06" | jq -e '(.schema_version|length>0) and (.last_refresh|length>0)' && echo "OK"

          echo "`n== /api/yahoo/me test (should be 401 without y_at) =="
          curl -sSD - "$BASE/api/yahoo/me" -o /dev/null | grep -Ei '^(HTTP/)' || true

          echo "`n== Weekly smoke test completed =="

      - name: Post results to Notion (if configured)
        if: success()
        run: |
          echo "✅ Weekly smoke test passed - all endpoints healthy"
          # Add Notion posting logic here if needed

      - name: Post failure to Notion (if configured)
        if: failure()
        run: |
          echo "❌ Weekly smoke test failed - check logs"
          # Add Notion posting logic here if needed
